#ifndef PHILIPSREMOTE_GLOBAL_H
#define PHILIPSREMOTE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHILIPSREMOTE_LIBRARY)
#  define PHILIPSREMOTESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PHILIPSREMOTESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PHILIPSREMOTE_GLOBAL_H
